src/com/product/model/ProductDAO_interface.java
package com.product.model;

import java.util.*;


public interface ProductDAO_interface {
	
	  public void insert(ProductVO productVO);
	  public void update(ProductVO productVO);
	  public void delete(Integer product_no);
	  public ProductVO findByPrimaryKey(Integer product_no);
	  public List<ProductVO> getAll();
	  public Integer getCountBycategory(Integer product_category_no);
	  public Set<ProductVO> findByProductName(String product_name);
	  public void update_status(Integer product_no);
	  public void update_status2(Integer product_no);
}

src/com/product/model/ProductService.java
package com.product.model;

import java.util.List;
import java.util.Set;

import com.order_item.model.Order_itemVO;
import com.orders.model.OrdersVO;

public class ProductService {

	private ProductDAO_interface dao;

	public ProductService() {
		dao = new ProductDAO();
	}

	public ProductVO addProduct(String product_name, String product_intro, Integer product_point,
			Integer product_stock_quantity, byte[] product_img, Integer product_status, 
			Integer product_category_no, String product_img_name, Integer product_discount_no,
			Integer product_discount_detail_rate,String product_discount_detail_coupon,
			Integer product_discount_detail_minus,Integer product_discount_detail_buy_count,
			Integer product_discount_detail_get_count) {

		ProductVO productVO = new ProductVO();
		
		productVO.setProduct_name(product_name);
		productVO.setProduct_intro(product_intro);
		productVO.setProduct_point(product_point);
		productVO.setProduct_stock_quantity(product_stock_quantity);
		productVO.setProduct_img(product_img);
		productVO.setProduct_status(product_status);
		productVO.setProduct_category_no(product_category_no);
		productVO.setProduct_img_name(product_img_name);
		productVO.setProduct_discount_no(product_discount_no);
		productVO.setProduct_discount_detail_rate(product_discount_detail_rate);
		productVO.setProduct_discount_detail_coupon(product_discount_detail_coupon);
		productVO.setProduct_discount_detail_minus(product_discount_detail_minus);
		productVO.setProduct_discount_detail_buy_count(product_discount_detail_buy_count);
		productVO.setProduct_discount_detail_get_count(product_discount_detail_get_count);
		
		dao.insert(productVO);

		return productVO;
	}

	public ProductVO updateProduct(Integer product_no, String product_name, String product_intro, Integer product_point,
			Integer product_stock_quantity, byte[] product_img, Integer product_status, Integer product_category_no, 
			String product_img_name,Integer product_discount_no,Integer product_discount_detail_rate,String product_discount_detail_coupon,
			Integer product_discount_detail_minus,Integer product_discount_detail_buy_count,
			Integer product_discount_detail_get_count) {
		
		ProductVO productVO = new ProductVO();
		
		productVO.setProduct_no(product_no);
		productVO.setProduct_name(product_name);
		productVO.setProduct_intro(product_intro);
		productVO.setProduct_point(product_point);
		productVO.setProduct_stock_quantity(product_stock_quantity);
		productVO.setProduct_img(product_img);
		productVO.setProduct_status(product_status);
		productVO.setProduct_category_no(product_category_no);
		productVO.setProduct_img_name(product_img_name);
		productVO.setProduct_discount_no(product_discount_no);
		productVO.setProduct_discount_detail_rate(product_discount_detail_rate);
		productVO.setProduct_discount_detail_coupon(product_discount_detail_coupon);
		productVO.setProduct_discount_detail_minus(product_discount_detail_minus);
		productVO.setProduct_discount_detail_buy_count(product_discount_detail_buy_count);
		productVO.setProduct_discount_detail_get_count(product_discount_detail_get_count);
		
		dao.update(productVO);

		return productVO;
	}
	

	public void deleteProduct(Integer product_no) {
		dao.delete(product_no);
	}

	public ProductVO getOneProduct(Integer product_no) {
		return dao.findByPrimaryKey(product_no);
	}

	public List<ProductVO> getAll() {
		return dao.getAll();
	}
	
	public Integer getCountBycategory(Integer product_category_no) {
		return dao.getCountBycategory(product_category_no);
	}
	
	public Set<ProductVO> findByProductName(String product_name) {
		return dao.findByProductName(product_name);
	}
	
	public void  update_statusProduct(Integer product_no) {
		dao.update_status(product_no);
	}
	
	public void  update_statusProduct2(Integer product_no) {
		dao.update_status2(product_no);
	}
}

src/com/product/controller/ProductServlet.java
package com.product.controller;

import java.io.*;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.*;

import javax.servlet.*;
import javax.servlet.annotation.MultipartConfig;
import javax.servlet.http.*;

import com.article.model.ArticleService;
import com.order_item.model.Order_itemVO;
import com.orders.model.OrdersService;
import com.orders.model.OrdersVO;
import com.product.model.*;
import com.product_category.model.Product_categoryService;
import com.product_category.model.Product_categoryVO;

import shopping.product;
@MultipartConfig(fileSizeThreshold = 1024 * 1024, maxFileSize = 10 * 1024 * 1024, maxRequestSize = 5 * 5 * 1024 * 1024)

public class ProductServlet extends HttpServlet {

	public void doGet(HttpServletRequest req, HttpServletResponse res)
			throws ServletException, IOException {
		
		doPost(req, res);
	}

	public void doPost(HttpServletRequest req, HttpServletResponse res)
			throws ServletException, IOException {

		req.setCharacterEncoding("UTF-8");
		String action = req.getParameter("action");

		if ("getOne_For_Display".equals(action)) {

			List<String> errorMsgs = new LinkedList<String>();
		
			req.setAttribute("errorMsgs", errorMsgs);

			try {
				/***************************1.接收請求參數 - 輸入格式的錯誤處理**********************/
				String str = req.getParameter("product_no");
				if (str == null || (str.trim()).length() == 0) {
					errorMsgs.add("請輸入產品編號");
				}
				
				if (!errorMsgs.isEmpty()) {
					RequestDispatcher failureView = req
							.getRequestDispatcher("/product_list/product_homePage.jsp");
					failureView.forward(req, res);
					return;
				}
				
				Integer product_no = null;
				try {
					product_no = new Integer(str);
				} catch (Exception e) {
					errorMsgs.add("產品編號格式不正確");
				}
				
				if (!errorMsgs.isEmpty()) {
					RequestDispatcher failureView = req
							.getRequestDispatcher("/product_list/product_homePage.jsp");
					failureView.forward(req, res);
					return;
				}
				
				/***************************2.開始查詢資料*****************************************/
				ProductService productSvc = new ProductService();
				ProductVO productVO = productSvc.getOneProduct(product_no);
				if (productVO == null) {
					errorMsgs.add("查無資料");
				}
				
				if (!errorMsgs.isEmpty()) {
					RequestDispatcher failureView = req
							.getRequestDispatcher("/product_list/product_homePage.jsp");
					failureView.forward(req, res);
					return;
				}
				
				/***************************3.查詢完成,準備轉交(Send the Success view)*************/
				req.setAttribute("productVO", productVO); 
				String url = "/product_list/product_info.jsp";
				RequestDispatcher successView = req.getRequestDispatcher(url); 
				successView.forward(req, res);

				/***************************其他可能的錯誤處理*************************************/
			} catch (Exception e) {
				errorMsgs.add("無法取得資料:" + e.getMessage());
				RequestDispatcher failureView = req
						.getRequestDispatcher("/product_list/product_homePage.jsp");
				failureView.forward(req, res);
			}
		}
		
		
		if ("getOne_For_Update".equals(action)) { 

			List<String> errorMsgs = new LinkedList<String>();
			
			req.setAttribute("errorMsgs", errorMsgs);
			
			try {
				/***************************1.接收請求參數****************************************/
				Integer product_no = new Integer(req.getParameter("product_no"));
				/***************************2.開始查詢資料****************************************/
				ProductService productSvc = new ProductService();
				ProductVO productVO = productSvc.getOneProduct(product_no);
				
				/***************************3.查詢完成,準備轉交(Send the Success view)************/
				req.setAttribute("productVO", productVO);
				String url = "/product/update_product_input.jsp";
				RequestDispatcher successView = req.getRequestDispatcher(url);
				successView.forward(req, res);

				/***************************其他可能的錯誤處理**********************************/
			} catch (Exception e) {
				errorMsgs.add("無法取得要修改的資料:" + e.getMessage());
				RequestDispatcher failureView = req
						.getRequestDispatcher("/product/listOneProduct.jsp");
				failureView.forward(req, res);
			}
		}
		
		
		
		if ("update".equals(action)) { 
			System.out.println("進來update");
			List<String> errorMsgs = new LinkedList<String>();
		
			req.setAttribute("errorMsgs", errorMsgs);
		
			try {
				/***************************1.接收請求參數 - 輸入格式的錯誤處理**********************/
				Integer product_no = new Integer(req.getParameter("product_no").trim());
				
				String product_name = req.getParameter("product_name").trim();
	
				String product_intro = req.getParameter("product_intro").trim();
				System.out.println(product_intro);
				Integer product_point = null;
				try {
					product_point = new Integer(req.getParameter("product_point").trim());
				} catch (NumberFormatException e) {
					product_point = 0;
					errorMsgs.add("商品價格請填數字.");
				}

				Integer product_stock_quantity = null;
				try {
					product_stock_quantity = new Integer(req.getParameter("product_stock_quantity").trim());
				} catch (NumberFormatException e) {
					product_stock_quantity = 0;
					errorMsgs.add("商品庫存請填數字.");
				}

				
				Integer product_status = new Integer(req.getParameter("product_status").trim());
				
				Integer product_category_no = new Integer(req.getParameter("product_category_no").trim());
				
				
				ProductService productSvc = new ProductService();
				
				ProductVO productVO2 = productSvc.getOneProduct(product_no);
				
				String filename = productVO2.getProduct_img_name();
				
				
				byte[] data = null;
				
				if(!((req.getPart("product_img")).getSize()==0)) {
					//這邊如果有選擇檔案就會進入一般上傳,"filename"會被取代
					 Part file = req.getPart("product_img");
						
				     filename = file.getSubmittedFileName();		   
	    
				     String uploadPath = "C:/upload/"+filename;	     
				     
				     FileOutputStream fos = new FileOutputStream(uploadPath);
				     InputStream is = file.getInputStream();     
				     
				     data = new byte[is.available()];
				     is.read(data);
				     fos.write(data);
				     fos.close();    	
				}
				
				Integer product_discount_no = new Integer(req.getParameter("product_discount_no").trim());
				
				
				Integer product_discount_detail_rate = null;
				try {
					if(product_discount_no != 1) {
						product_discount_detail_rate = 0;
					}else {
						product_discount_detail_rate = new Integer(req.getParameter("product_discount_detail_rate").trim());
					}
				} catch (NumberFormatException e) {
					product_discount_detail_rate = 0;
					errorMsgs.add("商品折扣請填數字.");
				}
				
				String product_discount_detail_coupon = null;
				
				if(product_discount_no != 2) {
					product_discount_detail_coupon = "";
				}else {
					product_discount_detail_coupon = req.getParameter("product_discount_detail_coupon").trim();
				}
						
				
				Integer product_discount_detail_minus = null;
				try {
					
					if(product_discount_no != 2) {
						product_discount_detail_minus = 0;
					}else {
						product_discount_detail_minus = new Integer(req.getParameter("product_discount_detail_minus").trim());
					}
				} catch (NumberFormatException e) {
					product_discount_detail_minus = 0;
					errorMsgs.add("商品折價請填數字.");
				}
				
				Integer product_discount_detail_buy_count = null;
				try {
					if(product_discount_no != 3) {
						product_discount_detail_buy_count = 1;
					}else {
						product_discount_detail_buy_count = new Integer(req.getParameter("product_discount_detail_buy_count").trim());
					}				
				} catch (NumberFormatException e) {
					product_discount_detail_buy_count = 0;
					errorMsgs.add("需購數量請填數字.");
				}
				
				Integer product_discount_detail_get_count = null;
				try {
					if(product_discount_no != 3) {
						product_discount_detail_get_count = 0;
					}else {
						product_discount_detail_get_count = new Integer(req.getParameter("product_discount_detail_get_count").trim());
					}	
				} catch (NumberFormatException e) {
					product_discount_detail_get_count = 0;
					errorMsgs.add("贈送數量請填數字.");
				}
				
				
				
				
				ProductVO productVO = new ProductVO();
				
				productVO.setProduct_no(product_no);
				productVO.setProduct_name(product_name);
				productVO.setProduct_intro(product_intro);
				productVO.setProduct_point(product_point);
				productVO.setProduct_stock_quantity(product_stock_quantity);
				productVO.setProduct_img(data);
				productVO.setProduct_status(product_status);
				productVO.setProduct_category_no(product_category_no);
				productVO.setProduct_img_name(filename);
				productVO.setProduct_discount_no(product_discount_no);
				productVO.setProduct_discount_detail_rate(product_discount_detail_rate);
				productVO.setProduct_discount_detail_coupon(product_discount_detail_coupon);
				productVO.setProduct_discount_detail_minus(product_discount_detail_minus);
				productVO.setProduct_discount_detail_buy_count(product_discount_detail_buy_count);
				productVO.setProduct_discount_detail_get_count(product_discount_detail_get_count);
				

				
				if (!errorMsgs.isEmpty()) {
					req.setAttribute("productVO", productVO);
					RequestDispatcher failureView = req.getRequestDispatcher("/product/update_product_input.jsp");
					failureView.forward(req, res);
					return; 
				}
				
				/***************************2.開始修改資料*****************************************/
				productVO = productSvc.updateProduct(product_no, product_name, product_intro, product_point, product_stock_quantity,
										data,product_status, product_category_no, filename,product_discount_no,
										product_discount_detail_rate,product_discount_detail_coupon,
										product_discount_detail_minus, product_discount_detail_buy_count,
										product_discount_detail_get_count);
				
			
				
				/***************************3.修改完成,準備轉交(Send the Success view)*************/
				req.setAttribute("productVO", productVO);
				String url = "/product/listProd_back.jsp";

WebContent/product/addProduct.jsp
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page import="com.product.model.*"%>

<%
	ProductVO productVO = (ProductVO) request.getAttribute("productVO");
%>

<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<title>商品管理(後台)</title>
<link rel="stylesheet" href="${pageContext.request.contextPath}/product/css/addProduct.css">
<script type="text/javascript" src="${pageContext.request.contextPath}/ckeditor/ckeditor.js"></script>
<script src="${pageContext.request.contextPath}/product/vendors/jquery/jquery-3.6.0.min.js"></script>

</head>


<body>
		<header>
			<jsp:include page="/cms/header_asideMenu/cmsHeader.jsp" flush="true" />
		</header>
	
		<div>
			<jsp:include page="/cms/header_asideMenu/cmsAsideMenu.jsp" flush="true" />
	    </div>
	    
		<FORM METHOD="post" ACTION="product.do" name="form1" enctype="multipart/form-data">
			<div class="product_info" style="margin-right:130px;">
				<div class="product_title">
					<h1>新增產品</h1>
				</div>
				<div class="product_info_form">
					<div class="form1">商品封面照</div>
					<div class="product_pic_upload">
						<ul class="picture_list"></ul>
						<a href="javascript:void(0)"> 
							<img src="${pageContext.request.contextPath}/product/img/新增圖片.png" id="my-img"> 
							<input type="file" name="product_img" id="img-upload">
						</a>
					</div>
					<div class="form1">
					名稱
					<c:if test="${not empty errorMsgs}">						
							<c:forEach var="message" items="${name_errorMsgs}">
									<span style="color:red; font-size:12px;">${message}</span>
							</c:forEach>							
					</c:if>
					</div>
					<div class="form2">
						<input type="TEXT" name="product_name" size="30" class="input_css"
							value="<%=(productVO == null) ? "" : productVO.getProduct_name()%>" />
					</div>
					<div class="form1">
					價格
					<c:if test="${not empty errorMsgs}">						
							<c:forEach var="message" items="${point_errorMsgs}">
									<span style="color:red; font-size:12px;">${message}</span>
							</c:forEach>							
					</c:if>
					</div>
					<div class="form2">
						<input type="TEXT" name="product_point" size="15"
							value="<%=(productVO == null) ? "" : productVO.getProduct_point()%>" />
					</div>
					<div class="form1">
					庫存數量
					<c:if test="${not empty errorMsgs}">						
							<c:forEach var="message" items="${stock_quantity_errorMsgs}">
									<span style="color:red; font-size:12px;">${message}</span>
							</c:forEach>							
					</c:if>
					
					</div>
					<div class="form2">
						<input type="TEXT" name="product_stock_quantity" size="15"
							value="<%=(productVO == null) ? "" : productVO.getProduct_stock_quantity()%>" />
					</div>
					
					
					<div class="form1">商品介紹</div>
					<div class="form2">
						<textarea name="product_intro" rows="15" cols="80" class="ckeditor"></textarea>
					</div>
					<jsp:useBean id="product_categorySvc" scope="page" class="com.product_category.model.Product_categoryService" />
					<div class="form1">系列</div>
					<div class="form2">
						<select size="1" name="product_category_no" class="select">
							<c:forEach var="product_categoryVO" items="${product_categorySvc.all}">
								<option value="${product_categoryVO.product_category_no}"
									${(productVO.product_category_no==product_categoryVO.product_category_no)? 'selected':'' }>${product_categoryVO.product_category_name}
							</c:forEach>
						</select>
					</div>
					<div class="form1">上架狀態</div>
					<div class="form2">
						<input type="RADIO" name="product_status" size="45" value="0" checked />下架 
							<input type="RADIO" name="product_status" size="45" value="1" />上架
					</div>

				</div>
				</div>
<!-- 			-----------------------------------------商品折扣----------------------------------------- -->
			<div class="product_info" style="height:500px; margin-right:130px;">
				<div class="product_title">
					<h1>優惠設定</h1>
				</div>
				<div class="product_info_form">
					
					
						<div class="form2">
							  <label>
							    <input type="radio" value="1" name="product_discount_no"/>
							     	折扣優惠
							  </label>							  
						</div>
						
						<div class="discount_1">
							優惠折數: <input type="NUMBER" name="product_discount_detail_rate" style="width:70px;" step="1" min="0" max="10" size="2">&nbsp;折
						</div>
						
						<div class="form2">
							  <label>
							    <input type="radio" value="2" name="product_discount_no"/>
							     	Coupon
							  </label>							  
						</div>
						
						<div class="discount_2">
							<div>設定Coupon代碼: <input type="TEXT" id="coupon" name="product_discount_detail_coupon" size="25"></div>
							<div class="random_code"><input id="autofill" type="button" onclick="RandomAutoFunction()" value="自動產生隨機代碼" size="3"></div>
							<div>減價: <input type="number" name="product_discount_detail_minus" style="width:120px;" step="1" min="0" size="3">&nbsp;元</div>
						</div>
						
						<div class="form2">
							  <label>
							    <input type="radio" value="3" name="product_discount_no"/>
							     	買X送x
							  </label>							  
						</div>
						
						<div class="discount_3">
							買<input type="number"style="width:70px;" step="1" min="1" name="product_discount_detail_buy_count" size="1">
							送<input type="number"style="width:70px;" step="1" min="0" name="product_discount_detail_get_count" size="1">
						</div>
						
						<div class="form2">
							  <label>
							    <input type="radio" value="4" class="ckbutton_checkbox" name="product_discount_no" checked/>
							     	不須設定優惠
							  </label>							  
						</div>


					<div class="product_save">
						<input type="hidden" name="action" value="insert"> 
						<input type="submit" value="儲存" class="product_save_submit">
						<a href='listProd_back.jsp'><input type="button" value="取消" class="product_save_submit" style="background-color:rgb(161, 161, 161);"></a>
					</div>
					
				</div>
			</div>
		</FORM>
	<script src="${pageContext.request.contextPath}/product/js/addProduct.js"></script>
	<script>
	// 優惠選擇填單顯示 
	$(document).ready(function(){ 
		$(".discount_1").hide();
        $(".discount_2").hide();
        $(".discount_3").hide();
	
	   $('input[name="product_discount_no"]').click(function(){
		        if($(this).attr("value")=="1"){
		            $(".discount_1").show();
		            $(".discount_2").hide();
		            $(".discount_3").hide();
		        }
		        if($(this).attr("value")=="2"){
		            $(".discount_1").hide();
		            $(".discount_2").show();
		            $(".discount_3").hide();
		        }
		        if($(this).attr("value")=="3"){
		            $(".discount_1").hide();
		            $(".discount_2").hide();
		            $(".discount_3").show();
		        }
		        if($(this).attr("value")=="4"){
		            $(".discount_1").hide();
		            $(".discount_2").hide();
		            $(".discount_3").hide();
		        }
		    });	   
		 });
	</script>
	
	
	<script>
	var characters="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	var passwordlength=8

		function generatepassword() {
		var password = ""
		var n = 0
		var randomnumber = 0
		while( n < passwordlength ) {
		n ++
		randomnumber = Math.floor(characters.length*Math.random());
		password += characters.substring(randomnumber,randomnumber + 1)
		}

		return password
		}
	
	function RandomAutoFunction() {
// 	    if (document.getElementById('autofill').click()) {
	        var randomNum = generatepassword();
	     
// 			alert(generatepassword());
	        document.getElementById('coupon').value = randomNum;
	   
// 	    } 
	}
	</script>
</body>

</html>

WebContent/product/listOneProduct_bak.jsp
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page import="com.product.model.*"%>
<%-- 此頁暫練習採用 Script 的寫法取值 --%>

<%
  ProductVO productVO = (ProductVO) request.getAttribute("productVO"); //EmpServlet.java(Concroller), 存入req的empVO物件
%>

<html>
<head>
<title>商品資料</title>
<h4><a href="select_page.jsp">回首頁</a></h4>
<style>
  table#table-1 {
	background-color: #CCCCFF;
    border: 2px solid black;
    text-align: center;
  }
  table#table-1 h4 {
    color: red;
    display: block;
    margin-bottom: 1px;
  }
  h4 {
    color: blue;
    display: inline;
  }
</style>

<style>
  table {
	width: 600px;
	background-color: white;
	margin-top: 5px;
	margin-bottom: 5px;
  }
  table, th, td {
    border: 1px solid #CCCCFF;
  }
  th, td {
    padding: 5px;
    text-align: center;
  }
</style>

</head>
<body bgcolor='white'>

<h4>此頁暫練習採用 Script 的寫法取值:</h4>
<table id="table-1">
	<tr><td>
		 <h3>商品資料 - ListOneProduct.jsp</h3>
<!-- 		 <h4><a href="select_page.jsp"><img src="images/back1.gif" width="100" height="32" border="0">回首頁</a></h4> -->
	</td></tr>
</table>

<table>
	<tr>
		<th>商品編號</th>
		<th>商品名稱</th>
		<th>商品介紹</th>
		<th>商品價格</th>
		<th>庫存數量</th>
		<th>商品圖片</th>
		<th>上架狀態</th>
		<th>商品類別</th>
	</tr>
	<tr>
		<td>${productVO.product_no}</td>
		<td>${productVO.product_name}</td>
		<td>${productVO.product_intro}</td>
		<td>${productVO.product_point}</td>
		<td>${productVO.product_stock_quantity}</td>
		<td>${productVO.product_img}</td>
		<td>${productVO.product_status eq 1?"上架":"下架"}</td> 
		<c:if test="${productVO.product_category_no == 1}"><td>生活</td></c:if>
		<c:if test="${productVO.product_category_no == 2}"><td>飯店住宿</td></c:if>
		<c:if test="${productVO.product_category_no == 3}"><td>泡湯</td></c:if>
		<c:if test="${productVO.product_category_no == 4}"><td>獨享食光</td></c:if>
	</tr>
</table>

</body>
</html>

WebContent/product/product_listAll_view.jsp
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page import="java.util.*"%>
<%@ page import="com.orders.model.*"%>



<jsp:useBean id="product_categorySvc" scope="page" class="com.product_category.model.Product_categoryService" />
<jsp:useBean id="productSvc" scope="page" class="com.product.model.ProductService" />
<html lang="en">

<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>商品管理(後台)</title>
<script src="https://kit.fontawesome.com/d210246855.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="${pageContext.request.contextPath}/product/css/product_listAll_view.css">
<script src="${pageContext.request.contextPath}/product/vendors/jquery/jquery-3.6.0.min.js"></script>

</head>

<body>

<header>
	<jsp:include page="/cms/header_asideMenu/cmsHeader.jsp" flush="true" />
</header>
<div>
	<jsp:include page="/cms/header_asideMenu/cmsAsideMenu.jsp" flush="true" />
</div>

	<div class="main" style=" margin-right:130px;">
		<div class="listProd_content">
			<div class="product_title">
				<h1>商品編號: ${productVO.product_no}</h1>
				<button class="button1" onclick="location.href='${pageContext.request.contextPath}/product/listProd_back.jsp'">
					返回
				</button>
				<button class="button2">
					<i class="far fa-trash-alt"></i>&nbsp;&nbsp;刪除產品
				</button>
				<FORM METHOD="post" ACTION="<%=request.getContextPath()%>/product/product.do">
			    	<input type="submit" value="移除" onclick="javascript:return del();">
			     	<input type="hidden" name="product_no"  value="${productVO.product_no}">
			     	<input type="hidden" name="action" value="delete">
			    </FORM>
			</div>
		
			<table>
					<tr>
						<th colspan="5" style="text-align:center;">商品資料</th>
					</tr>	
					<tr>
						<th width="30px;" style="background-color:white;"></th>
						<th width="120px;" style="background-color:white;">商品編號</th>
						<th width="120px" style="background-color:white;">訂價</th>				
						<th width="250px;" style="background-color:white;">商品名稱</th>
						<th width="" style="background-color:white;">庫存</th>
					</tr>
							
					<tr>
						<td width="30px;"></td>
						<td width="120px;">${productVO.product_no}</td>					
						<td width="120px">${productVO.product_point} GP</td>
						<td width="250px;">${productVO.product_name}</td>
						<td width="">${productVO.product_stock_quantity}</td>		
					</tr>
			</table>
			<table>

					<tr>
						<th width="294px" style="background-color:white;"></th>				
						<th width="249px;" style="background-color:white;">上架狀態</th>
						<th width="" style="background-color:white;">系列</th>
	
					</tr>
					<tr>
						<td width="294px">
		                   	<img src="/upload/${productVO.product_img_name}">	            
						</td>
				
						
						<td width="249px;">${productVO.product_status eq 1?"上架":"下架"}</td>
						<td width="">
								<c:forEach var="product_categoryVO" items="${product_categorySvc.all}">
	                    			<c:if test="${product_categoryVO.product_category_no==productVO.product_category_no}">
		                   				${product_categoryVO.product_category_name}
	                    			</c:if>
	                			</c:forEach>
	                	</td>
						</tr>
			</table>
			<table>
					<tr>
						<th colspan="2" style="text-align:center;">商品介紹</th>
					</tr>
					<tr>
						<td width="30px;"></td>
						<td style=" height:300px;vertical-align: unset;padding-top:40px;">${productVO.product_intro}</td>
					</tr>
			</table>
		
		
			<div class="include_file">
			</div>
		</div>
	</div>
<%-- 	<script src="${pageContext.request.contextPath}/product/js/orders_listAll.js"></script> --%>
	<script>
	function del() {
		var msg = "您真的確定要刪除嗎？\n\n請確認！";
		if (confirm(msg)==true){
		return true;
		}else{
		return false;
		}
	}
	</script>
</body>

</html>